### ISSUE TITLE
文章目录Content可以调整为固定位置吗

### ISSUE THREAD

**Issue by strongduanmu** [halfrost/Prometheus#54]
您好，非常感谢您开发的ghost主题，我不太擅长前端，请问可以支持文章目录Content固定位置吗？😀
效果类似于：https://www.cnblogs.com/strongduanmu/p/antlr4_quick_start.html
文章上下查看的时候，能够根据目录切换，会比较方便一点。

**Comment by halfrost** [comment]
应该可以做。我有空的时候研究一下哈~（这个链接是你现在的 blog 么？）

**Comment by strongduanmu** [comment]
非常感谢，上面链接是我之前blog，现在已经切换到ghost了 😀

**Comment by halfrost** [comment]
@strongduanmu 我改好了，发布了一个新的 release，你试试看。看看有没有不满意的地方。https://github.com/halfrost/Prometheus/releases/tag/3.27.0

（大佬你新的博客地址是？我也看看这个主题应用到你的博客上样式如何，看看是否正常）

**Comment by strongduanmu** [comment]
@halfrost 太感谢啦，可以加个微信好友吗—— s1069550670？这个是我新的博客地址：https://strongduanmu.com/antlr-basic-introduction/，3.27.0版本我晚上回去试下。另外说明下，我不是大佬，纯属技术小弟🤣。

**Comment by halfrost** [comment]
@strongduanmu 加你了哈。其实我也不是前端开发，我主业是后端，前端就自己折腾的😉 勉强够用。

**Comment by strongduanmu** [comment]
非常感谢作者大大帮忙实现👍
