### ISSUE TITLE
搜索功能无法使用

### ISSUE THREAD

**Issue by Xunzhuo** [halfrost/Prometheus#59]
![image](https://user-images.githubusercontent.com/48784001/111864084-f64a5400-8999-11eb-9ac6-268c50c71ff7.png)

**Comment by halfrost** [comment]
@Xunzhuo 你是什么输入的呢？我这边试了几次，都可以呀。。

![image](https://user-images.githubusercontent.com/10825609/111864267-d8c9ba00-899a-11eb-813b-2e1351ec0691.png)

**Comment by Xunzhuo** [comment]
链接在这 http://blog.liuxunzhuo.top 你试试呢

halfrost ***@***.***> 于2021年3月20日周六 下午4:40写道：

**Comment by halfrost** [comment]
报错在这里。。好像是什么权限的原因。。主题里面我并没有特殊的设置。

![image](https://user-images.githubusercontent.com/10825609/111864567-9d2fef80-899c-11eb-9306-7658c380e750.png)

搜索的实现代码在这里：https://github.com/halfrost/Prometheus/blob/58815c204605b7f1c5fa8c35fe1547c1c375bc9f/assets/js/index.js#L212

我就是调用了 Ghost 一个 api，传了一些搜索参数。

**Comment by Xunzhuo** [comment]
收到 我去查查原因，谢谢~
