### ISSUE TITLE
Role of busuanzi.pure.mini.js Script

### ISSUE THREAD

**Issue by thekeviv** [halfrost/Prometheus#60]
Hi,
I loved your work. I plan on customizing it and use it for my own blog. When I deploy it with my own domain, it adds another cookie with busuanzi.ibruce.info domain name. 

I noticed that there is a script in  the default.hbs file 
```
<script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>
```
The page for the script was in Chinese but on translating, it seems it finds the visitor count. Interestingly though, the whole UI breaks if I remove this script. Can you explain what is the role of this script? I tried removing all references to this script (from the about footer) but it still breaks. I also tried bringing it locally by creating a file under the js folder which gulp then includes in the build but it still didn't fix the issue.

![image](https://user-images.githubusercontent.com/16347985/111935989-e9a12b00-8a81-11eb-9350-26ee4c23a42c.png)

**Comment by thekeviv** [comment]
It seems the issue was not with this script but with the script tag declaring the disqus_shortname variable. I think that variable is used in the disqus_comment file and that probably causes some issue. I am not planning to include comments for my clone so I removed those and the UI seems fine now after removing both the above mentioned script and the disqus script!

**Comment by halfrost** [comment]
@thekeviv Hi~busuanzi.pure.mini.js this file is the visitor count. You can delete this file, using google tag manager to couter visitors. Due to certain restrictions on Internet access to google services in China, we cannot use google normally. So we need to develop this counter component.

You can remove busuanzi.pure.mini.js, and delete related label about busuanzi in the footer. Then use `gulp upload` script to generate dist file.

Feel free to ask me if you have any questions.

**Comment by thekeviv** [comment]
I understand. Thank you so much @halfrost

**Comment by halfrost** [comment]
@thekeviv If you have finished, you can share the website url with me. I hope to see your great finished website. Have a nice day~ 🎉

**Comment by thekeviv** [comment]
You can see an in-progress version here: www.viveksharma.dev . I haven't finished it yet, it's mostly changing the links for now!

I come from a React background and started learning ghost today and landed on your theme and liked it so much! Your write up in the readme was also great! Your theme is very well organized into separate components and that makes editing it very easy.

PS - I think I want to build a version of Ghost where the UI layer of handlebars is replaced by Next.js or something. I'll let you know once I make some progress on it and maybe you can join me in that journey. Thank you for all your work! Cheers!
