### ISSUE TITLE
Can we support picture lazy load?

### ISSUE THREAD

**Issue by Xunzhuo** [halfrost/Prometheus#68]
![image](https://user-images.githubusercontent.com/48784001/119942177-19aa0480-bfc4-11eb-9f67-1d59e2c0a373.png)
When refreshing pages, pictures show like this in a short time
@halfrost

**Comment by halfrost** [comment]
This is the effect of lazy load.

**Comment by Xunzhuo** [comment]
sure~ https://www.liuxunzhuo.com thanks so much

**Comment by halfrost** [comment]
I check your website and the current performance is in line with expectations. This is lazy loading. Display the text first, then load the image. And only show the pictures visible in the window.

**Comment by Xunzhuo** [comment]
Ok my bad~ Thanks anyway,~
